/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MCIMX6Y2xxx08
package_id: MCIMX6Y2CVM08
mcu_data: i_mx_2_0
processor_version: 6.0.1
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "iomux_config.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'false', coreID: ca7}
- pin_list:
  - {pin_num: F3, peripheral: GPIO4, signal: 'gpio_io, 20', pin_signal: CSI_HSYNC, PUS: no_init, ODE: ENABLED}
  - {pin_num: E4, peripheral: GPIO4, signal: 'gpio_io, 21', pin_signal: CSI_DATA00, PUS: no_init, ODE: ENABLED}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-A7[ca7] */
  /* IOMUXC_SW_MUX_CTL_PAD_CSI_DATA00 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[104U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(5U);
  /* IOMUXC_SW_MUX_CTL_PAD_CSI_HSYNC register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[103U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(5U);
  /* IOMUXC_SW_PAD_CTL_PAD_CSI_DATA00 register modification value */
  IOMUXC_BASE_PTR->SW_PAD_CTL_PAD[104] = 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(6U) |
                        IOMUXC_SW_PAD_CTL_PAD_SPEED(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_ODE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PKE_MASK;
  /* IOMUXC_SW_PAD_CTL_PAD_CSI_HSYNC register modification value */
  IOMUXC_BASE_PTR->SW_PAD_CTL_PAD[103] = 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(6U) |
                        IOMUXC_SW_PAD_CTL_PAD_SPEED(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_ODE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PKE_MASK;
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
